#!/bin/sh -e

TEST_DIR=$(readlink -f $(dirname $0))

if [ -z "$AUTOPKGTEST_TMP" ]; then
  AUTOPKGTEST_TMP=$(mktemp -d)
  trap 'rm -rf $AUTOPKGTEST_TMP' 0
fi
cd $AUTOPKGTEST_TMP

if [ "${DEB_HOST_GNU_TYPE:-}" ]; then
  CC="$DEB_HOST_GNU_TYPE-${CC:-gcc}"
  PKG_CONFIG="$DEB_HOST_GNU_TYPE-pkg-config"
else
  CC="${CC:-gcc}"
  PKG_CONFIG=pkg-config
fi

echo '1..2'

$CC -o lsmod $TEST_DIR/lsmod.c \
  $($PKG_CONFIG --cflags --libs libkmod)
echo "ok 1 - build"

./lsmod
echo "ok 2 - run"

